"""Prometheus V10 Speculative Evolution — Sequential fork + prefix conditioning + early termination.

Inspired by SpecGen (arXiv:2606.17518):
- Fork non-reasoning generations at trigger points in the reasoning trace
- Prefix conditioning: speculative candidates inherit reasoning context
- Elastic resource pool: dynamic split between validation and profiling
- Early termination: stop reasoning when satisfactory candidate emerges

NOTE: Current implementation uses sequential fork dispatch (deque-based).
True parallel execution (ThreadPool/asyncio.gather) would be needed for
concurrent candidate generation, but the core SpecGen insight — speculative
forking at trigger points with prefix conditioning — is implemented here.
Parallel execution is an engineering optimization, not an algorithmic one.

Key difference from V9PRO:
- V9PRO engine.py: 12 layers execute serially, one mutation per layer
- V10 speculative_evolution.py: speculative forks + early termination at trigger points
"""

from __future__ import annotations

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class SpeculativeCandidate:
    """One candidate generated by speculative fork."""
    candidate_id: str = ""
    layer: int = 0
    prefix_context: str = ""     # reasoning prefix this was conditioned on
    trigger_point: str = ""      # what triggered this fork
    fitness: float = 0.0
    validated: bool = False
    profiled: bool = False
    created_at: float = field(default_factory=time.time)


@dataclass
class TriggerSignal:
    """A trigger signal in the reasoning trace that can fork a speculative generation."""
    signal_type: str = ""    # "design_decision", "code_block", "parameter_choice"
    content: str = ""
    layer: int = 0
    confidence: float = 0.5


class ForkController:
    """Monitor reasoning trace and fork speculative candidates at trigger points.

    Following SpecGen §6.1 (SpecController):
    - Parse reasoning output stream for trigger signals
    - Dispatch speculative generations conditioned on reasoning prefix
    - Adapt fork count to available resource capacity
    """

    TRIGGER_PATTERNS = {
        "design_decision": ["therefore", "we choose", "optimal strategy", "approach:"],
        "code_block": ["def ", "class ", "```", "import "],
        "parameter_choice": ["alpha=", "threshold=", "ratio=", "learning_rate="],
    }

    def __init__(self, max_forks_per_trigger: int = 3) -> None:
        self._max_forks = max_forks_per_trigger
        self._pending_forks: deque[SpeculativeCandidate] = deque()
        self._completed: list[SpeculativeCandidate] = []
        self._fork_id_counter: int = 0

    def scan_for_triggers(self, reasoning_prefix: str, layer: int) -> list[TriggerSignal]:
        """Scan reasoning prefix for trigger signals."""
        triggers: list[TriggerSignal] = []
        prefix_lower = reasoning_prefix.lower()

        for signal_type, patterns in self.TRIGGER_PATTERNS.items():
            for pattern in patterns:
                if pattern.lower() in prefix_lower:
                    triggers.append(TriggerSignal(
                        signal_type=signal_type,
                        content=pattern,
                        layer=layer,
                        confidence=0.7 if signal_type == "code_block" else 0.5,
                    ))
                    break  # one trigger per type per scan

        return triggers

    def fork_candidates(self, trigger: TriggerSignal, prefix: str,
                        available_capacity: int = 2) -> list[SpeculativeCandidate]:
        """Fork speculative candidates from a trigger signal."""
        n_forks = min(self._max_forks, max(1, available_capacity))
        candidates = []

        for _ in range(n_forks):
            self._fork_id_counter += 1
            candidate = SpeculativeCandidate(
                candidate_id=f"fork_{self._fork_id_counter}",
                layer=trigger.layer,
                prefix_context=prefix[-500:],  # last 500 chars of reasoning
                trigger_point=f"{trigger.signal_type}:{trigger.content}",
            )
            self._pending_forks.append(candidate)
            candidates.append(candidate)

        logger.info(f"Forked {n_forks} candidates at trigger '{trigger.signal_type}' (layer {trigger.layer})")
        return candidates

    def mark_validated(self, candidate_id: str, fitness: float) -> None:
        """Mark a candidate as validated with fitness score."""
        for c in self._pending_forks:
            if c.candidate_id == candidate_id:
                c.validated = True
                c.fitness = fitness
                self._completed.append(c)
                self._pending_forks.remove(c)
                return

    def get_pending(self) -> list[SpeculativeCandidate]:
        return list(self._pending_forks)

    def get_completed(self) -> list[SpeculativeCandidate]:
        return list(self._completed)

    @property
    def has_pending(self) -> bool:
        return len(self._pending_forks) > 0

    def stats(self) -> dict[str, Any]:
        return {
            "pending_forks": len(self._pending_forks),
            "completed_forks": len(self._completed),
            "total_forked": self._fork_id_counter,
        }


class ElasticResourcePool:
    """Dynamic resource allocation between validation and profiling.

    Following SpecGen §6.2 (ElasticScheduler):
    - One elastic pool split between validation and profiling
    - Reallocate based on arrival rates from previous iteration
    - Validation: last-arrival-first (later candidates carry more prefix context)
    - Profiling: FIFO (return feedback fast for freshest signal)
    """

    def __init__(self, total_capacity: int = 10) -> None:
        self._total = total_capacity
        self._validation_capacity = total_capacity // 2
        self._profiling_capacity = total_capacity - self._validation_capacity
        self._validation_queue: deque[SpeculativeCandidate] = deque()
        self._profiling_queue: deque[SpeculativeCandidate] = deque()

    def enqueue_validation(self, candidate: SpeculativeCandidate) -> bool:
        """Add a candidate to validation queue. Returns False if queue full."""
        if len(self._validation_queue) >= self._validation_capacity:
            return False
        self._validation_queue.append(candidate)
        return True

    def enqueue_profiling(self, candidate: SpeculativeCandidate) -> bool:
        """Add a candidate to profiling queue. Returns False if queue full."""
        if len(self._profiling_queue) >= self._profiling_capacity:
            return False
        self._profiling_queue.append(candidate)
        return True

    def next_to_validate(self) -> SpeculativeCandidate | None:
        """Get next candidate for validation (last-arrival-first)."""
        if self._validation_queue:
            return self._validation_queue.pop()  # LIFO for validation
        return None

    def next_to_profile(self) -> SpeculativeCandidate | None:
        """Get next candidate for profiling (FIFO)."""
        if self._profiling_queue:
            return self._profiling_queue.popleft()  # FIFO for profiling
        return None

    def reallocate(self, validation_arrival_rate: float, profiling_arrival_rate: float) -> None:
        """Reallocate pool sizes based on arrival rates."""
        total_rate = validation_arrival_rate + profiling_arrival_rate
        if total_rate > 0:
            self._validation_capacity = max(1, int(self._total * validation_arrival_rate / total_rate))
            self._profiling_capacity = self._total - self._validation_capacity

    def stats(self) -> dict[str, Any]:
        return {
            "total_capacity": self._total,
            "validation_capacity": self._validation_capacity,
            "profiling_capacity": self._profiling_capacity,
            "validation_queue_len": len(self._validation_queue),
            "profiling_queue_len": len(self._profiling_queue),
            "utilization": (len(self._validation_queue) + len(self._profiling_queue)) / self._total,
        }


class SpeculativeEvolver:
    """Main speculative evolution controller.

    Combines ForkController + ElasticResourcePool with early termination.
    """

    def __init__(self, total_resource_capacity: int = 10,
                 early_termination_threshold: float = 0.0) -> None:
        self._fork_controller = ForkController()
        self._resource_pool = ElasticResourcePool(total_resource_capacity)
        self._early_termination_threshold = early_termination_threshold
        self._historical_avg_fitness: float = 0.0
        self._fitness_samples: deque[float] = deque(maxlen=20)

    def process_reasoning_chunk(self, chunk: str, layer: int) -> list[SpeculativeCandidate]:
        """Process a chunk of reasoning output. Fork candidates at trigger points."""
        triggers = self._fork_controller.scan_for_triggers(chunk, layer)
        candidates = []
        for trigger in triggers:
            available = self._resource_pool.stats()["profiling_capacity"]
            new_candidates = self._fork_controller.fork_candidates(trigger, chunk, available)
            for c in new_candidates:
                self._resource_pool.enqueue_validation(c)
            candidates.extend(new_candidates)
        return candidates

    def should_terminate_early(self, candidate_fitness: float) -> bool:
        """Check if reasoning should be terminated early.

        Following SpecGen: terminate when speculative candidate exceeds
        average speedup of previously generated candidates.
        """
        self._fitness_samples.append(candidate_fitness)
        if len(self._fitness_samples) < 3:
            return False

        current_avg = sum(self._fitness_samples) / len(self._fitness_samples)
        self._historical_avg_fitness = current_avg

        return candidate_fitness > current_avg + self._early_termination_threshold

    @property
    def fork_controller(self) -> ForkController:
        return self._fork_controller

    @property
    def resource_pool(self) -> ElasticResourcePool:
        return self._resource_pool

    def stats(self) -> dict[str, Any]:
        return {
            "forks": self._fork_controller.stats(),
            "resources": self._resource_pool.stats(),
            "historical_avg_fitness": self._historical_avg_fitness,
        }
